# -------------------------------------------------------------------------
# Email Account Information
# -------------------------------------------------------------------------
# This file lets you configure your email accounts and aliases
#