# -------------------------------------------------------------------------
# URI ROUTING
# -------------------------------------------------------------------------
# This file lets you re-map URI requests to specific controller functions.
#
# Typically there is a one-to-one relationship between a URL string
# and its corresponding controller class/method. The segments in a
# URL normally follow this pattern:
#
# 	www.your-site.com/class/method/id/
#
# In some instances, however, you may want to remap this relationship
# so that a different class/function is called than the one
# corresponding to the URL.

#Product Admin


Product_Manager/Audio/(\w+)/(\S+) : Product_Manager_Audio/$1/$2
Product_Manager/Audio/(\S+) : Product_Manager_Audio/$1
Product_Manager/Audio : Product_Manager_Audio


Config_Editor/Init_Var/(\w+)/(\S+) : Init_Var_Editor/$1/$2
Config_Editor/Init_Var/(\S+) : Init_Var_Editor/$1
Config_Editor/Init_Var : Init_Var_Editor
